{"name": "test_41", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_pytest_allure.test_allure_step.TestEditPage object at 0x0000020099B7F820>\n\n    def test_41(self):\n        \"\"\"失败用例41\"\"\"\n        print(\"失败用例41\")\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_pytest_allure\\test_allure_step.py:58: AssertionError"}, "description": "失败用例41", "attachments": [{"name": "stdout", "source": "ccb24c65-7f10-4993-874c-053bbe6463bd-attachment.txt", "type": "text/plain"}], "start": 1653038685937, "stop": 1653038685938, "uuid": "241e08a2-ce62-404f-9619-a77618106611", "historyId": "c174a9f958713b179ebdc0c28270b169", "testCaseId": "d1a73eb9d7234963baece1dd7a2793b2", "fullName": "test_pytest_allure.test_allure_step.TestEditPage#test_41", "labels": [{"name": "feature", "value": "test"}, {"name": "parentSuite", "value": "test_pytest_allure"}, {"name": "suite", "value": "test_allure_step"}, {"name": "subSuite", "value": "TestEditPage"}, {"name": "host", "value": "PC-20210510KUZF"}, {"name": "thread", "value": "19040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_allure.test_allure_step"}]}