{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "@allure.feature('test_broken') #模块名\n    def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_pytest_allure\\test_allure02.py:54: Exception"}, "start": 1653276474490, "stop": 1653276474490, "uuid": "61ac1b4b-54e7-45b1-8aff-5442fd2c6f8d", "historyId": "90c26e612040887e04163b9df2e39a9f", "testCaseId": "ee63c448812f05f606e17d62926f4f8e", "fullName": "test_pytest_allure.test_allure02#test_broken", "labels": [{"name": "feature", "value": "test_broken"}, {"name": "parentSuite", "value": "test_pytest_allure"}, {"name": "suite", "value": "test_allure02"}, {"name": "host", "value": "PC-20210510KUZF"}, {"name": "thread", "value": "13068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_allure.test_allure02"}]}