{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@allure.feature('test_failure') #模块名\n    def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_pytest_allure\\test_allure02.py:45: AssertionError"}, "description": "this test fails", "start": 1653276474288, "stop": 1653276474289, "uuid": "ec03740b-5891-4c5e-94ef-d6b37309ba9a", "historyId": "6e842a63c5073bf0cd031d3868a41693", "testCaseId": "42b82a4ed70532f02890244bc580e5a9", "fullName": "test_pytest_allure.test_allure02#test_failure", "labels": [{"name": "feature", "value": "test_failure"}, {"name": "parentSuite", "value": "test_pytest_allure"}, {"name": "suite", "value": "test_allure02"}, {"name": "host", "value": "PC-20210510KUZF"}, {"name": "thread", "value": "13068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_allure.test_allure02"}]}