{"name": "test_xfail_expected_failure", "status": "skipped", "statusDetails": {"message": "XFAIL 该功能尚未实现\n\nAssertionError: assert False", "trace": "@allure.feature('test_xfail_expected_failure')\n    @pytest.mark.xfail(reason='该功能尚未实现')\n    def test_xfail_expected_failure():\n        print(\"该功能尚未实现\")\n>       assert False\nE       assert False\n\ntest_pytest_allure\\test_allure02.py:63: AssertionError"}, "attachments": [{"name": "stdout", "source": "f8e634d5-de88-4b0a-8192-86386aafd3c9-attachment.txt", "type": "text/plain"}], "start": 1653276474507, "stop": 1653276474507, "uuid": "9e6cd0e6-8160-420f-ace0-00695cdcd024", "historyId": "d80cdca7a3f9505670a49595539ed159", "testCaseId": "299190ec3245e983adbf3bcf69168f5c", "fullName": "test_pytest_allure.test_allure02#test_xfail_expected_failure", "labels": [{"name": "feature", "value": "test_xfail_expected_failure"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='该功能尚未实现')"}, {"name": "parentSuite", "value": "test_pytest_allure"}, {"name": "suite", "value": "test_allure02"}, {"name": "host", "value": "PC-20210510KUZF"}, {"name": "thread", "value": "13068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_allure.test_allure02"}]}