{"name": "test_xfail_unexpected_pass", "status": "passed", "statusDetails": {"message": "XPASS 该Bug尚未修复"}, "attachments": [{"name": "stdout", "source": "477c710c-387f-4224-a952-654238010e60-attachment.txt", "type": "text/plain"}], "start": 1653276474524, "stop": 1653276474526, "uuid": "1a114268-4cf3-48f3-b1ad-0b440a146b46", "historyId": "a0bb36a96ae016632663cebafca3353d", "testCaseId": "e9b6e1f8cb1036e0ba048fcd2f3b7e4d", "fullName": "test_pytest_allure.test_allure02#test_xfail_unexpected_pass", "labels": [{"name": "feature", "value": "test_xfail_unexpected_pass"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='该Bug尚未修复')"}, {"name": "parentSuite", "value": "test_pytest_allure"}, {"name": "suite", "value": "test_allure02"}, {"name": "host", "value": "PC-20210510KUZF"}, {"name": "thread", "value": "13068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_allure.test_allure02"}]}